wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 1
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_episode_storage:
  desc: null
  value: None
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_obs:
  desc: null
  value: "[[[7.19100e+03 1.09590e+05 0.00000e+00 0.00000e+00 1.00000e+00\n   0.00000e+00]\n\
    \  [7.18405e+03 3.81630e+04 0.00000e+00 0.00000e+00 1.00000e+00\n   0.00000e+00]\n\
    \  [7.19500e+03 4.28060e+04 0.00000e+00 0.00000e+00 1.00000e+00\n   0.00000e+00]\n\
    \  [7.16610e+03 3.94090e+04 7.19239e+03 0.00000e+00 1.00000e+00\n   0.00000e+00]\n\
    \  [7.15790e+03 3.03560e+04 7.18616e+03 0.00000e+00 1.00000e+00\n   0.00000e+00]\n\
    \  [7.15300e+03 2.29970e+04 7.17767e+03 0.00000e+00 1.00000e+00\n   0.00000e+00]\n\
    \  [7.15200e+03 1.75680e+04 7.17288e+03 0.00000e+00 1.00000e+00\n   0.00000e+00]\n\
    \  [7.16600e+03 3.60500e+04 7.16710e+03 0.00000e+00 1.00000e+00\n   0.00000e+00]\n\
    \  [7.16220e+03 1.29070e+04 7.16568e+03 0.00000e+00 1.00000e+00\n   0.00000e+00]\n\
    \  [7.15615e+03 1.51980e+04 7.16565e+03 0.00000e+00 1.00000e+00\n   0.00000e+00]\n\
    \  [7.15600e+03 1.57460e+04 7.16934e+03 0.00000e+00 1.00000e+00\n   0.00000e+00]\n\
    \  [7.17100e+03 1.92940e+04 7.16983e+03 0.00000e+00 1.00000e+00\n   0.00000e+00]]]"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x150b616d0>
_n_calls:
  desc: null
  value: 0
_n_updates:
  desc: null
  value: 0
_num_timesteps_at_start:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 1000000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1672867738.216607
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 16
      - 22
      - 23
      - 34
      4: 3.8.15
      5: 0.13.7
      8:
      - 1
      - 4
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Discrete(2)
actor:
  desc: null
  value: None
algo:
  desc: null
  value: DQN
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
batch_size:
  desc: null
  value: 32
buffer_size:
  desc: null
  value: 1000000
device:
  desc: null
  value: cpu
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x1508ca910>
env_id:
  desc: null
  value: Stocks-v0
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
eval_env:
  desc: null
  value: None
exploration_final_eps:
  desc: null
  value: 0.05
exploration_fraction:
  desc: null
  value: 0.1
exploration_initial_eps:
  desc: null
  value: 1.0
exploration_rate:
  desc: null
  value: 0.0
exploration_schedule:
  desc: null
  value: <function get_linear_fn.<locals>.func at 0x150936310>
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0001
learning_starts:
  desc: null
  value: 50000
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x1509368b0>
max_grad_norm:
  desc: null
  value: 10
n_envs:
  desc: null
  value: 1
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: "Box([[-inf -inf -inf -inf -inf -inf]\n [-inf -inf -inf -inf -inf -inf]\n\
    \ [-inf -inf -inf -inf -inf -inf]\n [-inf -inf -inf -inf -inf -inf]\n [-inf -inf\
    \ -inf -inf -inf -inf]\n [-inf -inf -inf -inf -inf -inf]\n [-inf -inf -inf -inf\
    \ -inf -inf]\n [-inf -inf -inf -inf -inf -inf]\n [-inf -inf -inf -inf -inf -inf]\n\
    \ [-inf -inf -inf -inf -inf -inf]\n [-inf -inf -inf -inf -inf -inf]\n [-inf -inf\
    \ -inf -inf -inf -inf]], [[inf inf inf inf inf inf]\n [inf inf inf inf inf inf]\n\
    \ [inf inf inf inf inf inf]\n [inf inf inf inf inf inf]\n [inf inf inf inf inf\
    \ inf]\n [inf inf inf inf inf inf]\n [inf inf inf inf inf inf]\n [inf inf inf\
    \ inf inf inf]\n [inf inf inf inf inf inf]\n [inf inf inf inf inf inf]\n [inf\
    \ inf inf inf inf inf]\n [inf inf inf inf inf inf]], (12, 6), float64)"
optimize_memory_usage:
  desc: null
  value: 'False'
policy:
  desc: null
  value: "DQNPolicy(\n  (q_net): QNetwork(\n    (features_extractor): FlattenExtractor(\n\
    \      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (q_net): Sequential(\n\
    \      (0): Linear(in_features=72, out_features=64, bias=True)\n      (1): ReLU()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): ReLU()\n\
    \      (4): Linear(in_features=64, out_features=2, bias=True)\n    )\n  )\n  (q_net_target):\
    \ QNetwork(\n    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n    )\n    (q_net): Sequential(\n      (0): Linear(in_features=72,\
    \ out_features=64, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=64,\
    \ out_features=2, bias=True)\n    )\n  )\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.dqn.policies.DQNPolicy'>
policy_kwargs:
  desc: null
  value: '{}'
policy_type:
  desc: null
  value: MlpPolicy
q_net:
  desc: null
  value: "QNetwork(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (q_net): Sequential(\n    (0): Linear(in_features=72, out_features=64,\
    \ bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=64, out_features=64,\
    \ bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=64, out_features=2,\
    \ bias=True)\n  )\n)"
q_net_target:
  desc: null
  value: "QNetwork(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1,\
    \ end_dim=-1)\n  )\n  (q_net): Sequential(\n    (0): Linear(in_features=72, out_features=64,\
    \ bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=64, out_features=64,\
    \ bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=64, out_features=2,\
    \ bias=True)\n  )\n)"
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x150d86820>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{}'
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: None
start_time:
  desc: null
  value: 1672867741922061000
target_update_interval:
  desc: null
  value: 10000
tau:
  desc: null
  value: 1.0
tensorboard_log:
  desc: null
  value: runs/1qh0xq5s
total_timesteps:
  desc: null
  value: 1000000
train_freq:
  desc: null
  value: 'TrainFreq(frequency=4, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde:
  desc: null
  value: 'False'
use_sde_at_warmup:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
