wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 1
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_obs:
  desc: null
  value: "[[[ 1.03201192e+01  7.78750090e+07  0.00000000e+00  0.00000000e+00\n   \
    \ 1.00000000e+00  1.00000000e+00]\n  [ 1.04525269e+01  9.66029360e+07  0.00000000e+00\
    \  0.00000000e+00\n    1.00000000e+00  0.00000000e+00]\n  [ 1.02386398e+01  1.00099436e+08\
    \  0.00000000e+00  0.00000000e+00\n    1.00000000e+00  1.00000000e+00]\n  [ 1.02182699e+01\
    \  7.69359300e+07  1.04072039e+01  0.00000000e+00\n    1.00000000e+00  0.00000000e+00]\n\
    \  [ 9.79303950e+00  8.62885840e+07  1.02905840e+01  0.00000000e+00\n    1.00000000e+00\
    \  0.00000000e+00]\n  [ 9.28123321e+00  1.79415702e+08  1.01332233e+01  0.00000000e+00\n\
    \    1.00000000e+00  0.00000000e+00]\n  [ 9.31942837e+00  1.27653926e+08  9.91067753e+00\
    \  0.00000000e+00\n    1.00000000e+00  0.00000000e+00]\n  [ 9.25576849e+00  1.89051436e+08\
    \  9.76604767e+00  0.00000000e+00\n    1.00000000e+00  0.00000000e+00]\n  [ 9.49003032e+00\
    \  1.72918416e+08  9.61530724e+00  0.00000000e+00\n    1.00000000e+00  0.00000000e+00]\n\
    \  [ 9.40091083e+00  9.22914480e+07  9.52720547e+00  0.00000000e+00\n    1.00000000e+00\
    \  0.00000000e+00]\n  [ 9.39072647e+00  1.00259719e+08  9.49970608e+00  0.00000000e+00\n\
    \    1.00000000e+00  0.00000000e+00]\n  [ 9.01642038e+00  1.38279150e+08  9.44623413e+00\
    \  0.00000000e+00\n   -1.00000000e+00  0.00000000e+00]]]"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x299704040>
_n_updates:
  desc: null
  value: 0
_num_timesteps_at_start:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 1000000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1673034964.112329
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 16
      - 22
      - 23
      - 34
      4: 3.8.15
      5: 0.13.7
      8:
      - 1
      - 4
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Discrete(2)
algo:
  desc: null
  value: A2C
device:
  desc: null
  value: cpu
ent_coef:
  desc: null
  value: 0.0
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x299704850>
env_id:
  desc: null
  value: Stocks-v0
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
eval_env:
  desc: null
  value: None
gae_lambda:
  desc: null
  value: 1.0
gamma:
  desc: null
  value: 0.99
learning_rate:
  desc: null
  value: 0.0007
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x299644af0>
max_grad_norm:
  desc: null
  value: 0.5
n_envs:
  desc: null
  value: 1
n_steps:
  desc: null
  value: 5
normalize_advantage:
  desc: null
  value: 'False'
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: "Box([[-inf -inf -inf -inf -inf -inf]\n [-inf -inf -inf -inf -inf -inf]\n\
    \ [-inf -inf -inf -inf -inf -inf]\n [-inf -inf -inf -inf -inf -inf]\n [-inf -inf\
    \ -inf -inf -inf -inf]\n [-inf -inf -inf -inf -inf -inf]\n [-inf -inf -inf -inf\
    \ -inf -inf]\n [-inf -inf -inf -inf -inf -inf]\n [-inf -inf -inf -inf -inf -inf]\n\
    \ [-inf -inf -inf -inf -inf -inf]\n [-inf -inf -inf -inf -inf -inf]\n [-inf -inf\
    \ -inf -inf -inf -inf]], [[inf inf inf inf inf inf]\n [inf inf inf inf inf inf]\n\
    \ [inf inf inf inf inf inf]\n [inf inf inf inf inf inf]\n [inf inf inf inf inf\
    \ inf]\n [inf inf inf inf inf inf]\n [inf inf inf inf inf inf]\n [inf inf inf\
    \ inf inf inf]\n [inf inf inf inf inf inf]\n [inf inf inf inf inf inf]\n [inf\
    \ inf inf inf inf inf]\n [inf inf inf inf inf inf]], (12, 6), float64)"
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor): MlpExtractor(\n  \
    \  (shared_net): Sequential()\n    (policy_net): Sequential(\n      (0): Linear(in_features=72,\
    \ out_features=64, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n\
    \      (0): Linear(in_features=72, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=64, out_features=2, bias=True)\n\
    \  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
  desc: null
  value: '{''optimizer_class'': <class ''torch.optim.rmsprop.RMSprop''>, ''optimizer_kwargs'':
    {''alpha'': 0.99, ''eps'': 1e-05, ''weight_decay'': 0}}'
policy_type:
  desc: null
  value: MlpPolicy
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x2a9cb0970>
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: None
start_time:
  desc: null
  value: 1673034967910474000
tensorboard_log:
  desc: null
  value: runs/l57u9tn8
total_timesteps:
  desc: null
  value: 1000000
use_sde:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
vf_coef:
  desc: null
  value: 0.5
